services:
  - type: worker
    name: discord-me-bot
    env: python
    pythonVersion: 3.11.9
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "python -u bot.py"
    autoDeploy: true
